sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache

language: scala

scala:
  - 2.11.5
  - 2.10.4
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

script:
  - sbt clean coverage test

after_success:
  - sbt coverageReport coveralls
